docs: Added Issue Templates
flyingsonu122/tarana pull request #28
Opened 2022-03-03 18:41 UTC by Pradumnasaraf

### Fix
 Closes #22

### Changes/Addition
- Add 3 issue templates
      - Bug
      - Doc
      - Feature

### Note 
Added these 3 labels if not present - `bug` `feature` `documentation` for auto labeling

2022-03-03 19:33 UTC, flyingsonu122 requested changes
create PR in **develop** branch

2022-03-04 03:19 UTC, Pradumnasaraf commented
@flyingsonu122 I have changed the branch please review.

2022-03-05 07:14 UTC, Pradumnasaraf commented
@flyingsonu122 @eshan1925, please check I have changed the branch please review.

2022-03-06 19:32 UTC, eshan1925 commented
LGTM.
PR Approved from my side @flyingsonu122.

2022-03-08 06:40 UTC, flyingsonu122 approved these changes

2022-03-08 06:40 UTC, merged

2022-03-08 06:44 UTC, Pradumnasaraf commented
Hey @flyingsonu122  thank you for merging, kindly please add the `Gssoc` labels
Thank you, Pradumna :)