Add Share Button
flyingsonu122/tarana pull request #35
Opened 2022-03-07 16:36 UTC by zugzwang03

So, the share button has been done with the required features essential. Sadly, I could not make it responsive to all devices, it would be better if some one else fixes that issue. 
Issue number #29 resolved.
The working can be checked from here : https://zugzwang03.github.io/tarana/
![clipboard](https://user-images.githubusercontent.com/95460021/157076850-3ad91bf5-bdf1-4ae8-9a9d-955737f76ed2.png)

2022-03-08 07:12 UTC, flyingsonu122 commented
@zugzwang03 please look up https://www.sonu.live/diwali-wishes/ 
do like that or more

2022-03-09 08:07 UTC, zugzwang03 commented
I made some changes, can you review it?
https://zugzwang03.github.io/tarana/

2022-03-09 10:15 UTC, flyingsonu122 commented
> I made some changes, can you review it? https://zugzwang03.github.io/tarana/

- remove youtube
- link should be like this **https://sonu.live/tarana/play.html?id={ID}**
- make it more responsive to all screen size



@sulogna2001 please work together with @zugzwang03 to make it happen

2022-03-11 13:56 UTC, flyingsonu122 commented on up.js
> +    links.innerHTML = All_song[index_no].path;
links.innerHTML = `https://sonu.live/tarana/play.html?id=${All_song[index_no].id}`;

2022-03-11 14:11 UTC, flyingsonu122 commented on up.js
> +        links.innerHTML = e.path;
![image](https://user-images.githubusercontent.com/51280276/157883840-da138550-1b59-42d5-b1ad-0b4b065e6200.png)

2022-03-11 14:12 UTC, flyingsonu122 requested changes
modify and see is it working

2022-03-11 17:47 UTC, zugzwang03 commented
Did those changes.

2022-03-11 18:38 UTC, flyingsonu122 approved these changes
Thank you @zugzwang03 for your contributions

2022-03-11 18:38 UTC, merged